export type LetterPicture = { icon: string; word: string };

export const LETTER_PICTURES: Record<string, readonly LetterPicture[]> = {
  A: [{ icon: '🍎', word: 'Apple' }, { icon: '🐜', word: 'Ant' }, { icon: '✈️', word: 'Airplane' }, { icon: '🥑', word: 'Avocado' }, { icon: '⚓️', word: 'Anchor' }],
  B: [{ icon: '⚽️', word: 'Ball' }, { icon: '🐻', word: 'Bear' }, { icon: '🍌', word: 'Banana' }, { icon: '🐝', word: 'Bee' }, { icon: '🦋', word: 'Butterfly' }],
  C: [{ icon: '🐱', word: 'Cat' }, { icon: '🚗', word: 'Car' }, { icon: '🎂', word: 'Cake' }, { icon: '🦀', word: 'Crab' }, { icon: '☁️', word: 'Cloud' }],
  D: [{ icon: '🐶', word: 'Dog' }, { icon: '🦆', word: 'Duck' }, { icon: '🥁', word: 'Drum' }, { icon: '🦕', word: 'Dinosaur' }, { icon: '🍩', word: 'Donut' }],
  E: [{ icon: '🐘', word: 'Elephant' }, { icon: '🥚', word: 'Egg' }, { icon: '🦅', word: 'Eagle' }, { icon: '🌍', word: 'Earth' }, { icon: '✉️', word: 'Envelope' }],
  F: [{ icon: '🐟', word: 'Fish' }, { icon: '🐸', word: 'Frog' }, { icon: '🌼', word: 'Flower' }, { icon: '🔥', word: 'Fire' }, { icon: '🦊', word: 'Fox' }],
  G: [{ icon: '🍇', word: 'Grapes' }, { icon: '🐐', word: 'Goat' }, { icon: '🎸', word: 'Guitar' }, { icon: '🎁', word: 'Gift' }, { icon: '🪿', word: 'Goose' }],
  H: [{ icon: '🏠', word: 'House' }, { icon: '🐴', word: 'Horse' }, { icon: '🎩', word: 'Hat' }, { icon: '❤️', word: 'Heart' }, { icon: '🚁', word: 'Helicopter' }],
  I: [{ icon: '🍦', word: 'Ice cream' }, { icon: '🧊', word: 'Ice' }, { icon: '🏝️', word: 'Island' }, { icon: '🦎', word: 'Iguana' }, { icon: '📥', word: 'Inbox' }],
  J: [{ icon: '🧃', word: 'Juice' }, { icon: '🪼', word: 'Jellyfish' }, { icon: '🫙', word: 'Jar' }, { icon: '✈️', word: 'Jet' }, { icon: '🕹️', word: 'Joystick' }],
  K: [{ icon: '🪁', word: 'Kite' }, { icon: '🐨', word: 'Koala' }, { icon: '🔑', word: 'Key' }, { icon: '🥝', word: 'Kiwi' }, { icon: '🦘', word: 'Kangaroo' }],
  L: [{ icon: '🦁', word: 'Lion' }, { icon: '🍋', word: 'Lemon' }, { icon: '🍃', word: 'Leaf' }, { icon: '🐞', word: 'Ladybug' }, { icon: '💡', word: 'Lamp' }],
  M: [{ icon: '🌙', word: 'Moon' }, { icon: '🐵', word: 'Monkey' }, { icon: '🐭', word: 'Mouse' }, { icon: '🍄', word: 'Mushroom' }, { icon: '🥛', word: 'Milk' }],
  N: [{ icon: '🪺', word: 'Nest' }, { icon: '👃', word: 'Nose' }, { icon: '📓', word: 'Notebook' }, { icon: '🐋', word: 'Narwhal' }, { icon: '🥜', word: 'Nut' }],
  O: [{ icon: '🐙', word: 'Octopus' }, { icon: '🍊', word: 'Orange' }, { icon: '🦉', word: 'Owl' }, { icon: '🌊', word: 'Ocean' }, { icon: '🦦', word: 'Otter' }],
  P: [{ icon: '🐷', word: 'Pig' }, { icon: '🍕', word: 'Pizza' }, { icon: '🐧', word: 'Penguin' }, { icon: '🍐', word: 'Pear' }, { icon: '🎹', word: 'Piano' }],
  Q: [{ icon: '👑', word: 'Queen' }, { icon: '❓', word: 'Question' }, { icon: '🪶', word: 'Quill' }, { icon: '🛏️', word: 'Quilt' }, { icon: '🤫', word: 'Quiet' }],
  R: [{ icon: '🐰', word: 'Rabbit' }, { icon: '🌈', word: 'Rainbow' }, { icon: '🤖', word: 'Robot' }, { icon: '🚀', word: 'Rocket' }, { icon: '🌹', word: 'Rose' }],
  S: [{ icon: '☀️', word: 'Sun' }, { icon: '⭐️', word: 'Star' }, { icon: '🐍', word: 'Snake' }, { icon: '🍓', word: 'Strawberry' }, { icon: '🐌', word: 'Snail' }],
  T: [{ icon: '🐢', word: 'Turtle' }, { icon: '🌳', word: 'Tree' }, { icon: '🚂', word: 'Train' }, { icon: '🐯', word: 'Tiger' }, { icon: '🍅', word: 'Tomato' }],
  U: [{ icon: '☂️', word: 'Umbrella' }, { icon: '🦄', word: 'Unicorn' }, { icon: '⬆️', word: 'Up' }, { icon: '🍴', word: 'Utensils' }, { icon: '🛸', word: 'UFO' }],
  V: [{ icon: '🎻', word: 'Violin' }, { icon: '🌋', word: 'Volcano' }, { icon: '🚐', word: 'Van' }, { icon: '🥕', word: 'Vegetables' }, { icon: '🦺', word: 'Vest' }],
  W: [{ icon: '🐳', word: 'Whale' }, { icon: '🍉', word: 'Watermelon' }, { icon: '⌚️', word: 'Watch' }, { icon: '🪱', word: 'Worm' }, { icon: '🛞', word: 'Wheel' }],
  X: [{ icon: '🎼', word: 'Xylophone' }, { icon: '🩻', word: 'X-ray' }, { icon: '❌', word: 'X mark' }, { icon: '🐿️', word: 'Xerus' }, { icon: '🐟', word: 'X-ray fish' }],
  Y: [{ icon: '🐂', word: 'Yak' }, { icon: '🧶', word: 'Yarn' }, { icon: '🪀', word: 'Yo-yo' }, { icon: '💛', word: 'Yellow' }, { icon: '⛵️', word: 'Yacht' }],
  Z: [{ icon: '🦓', word: 'Zebra' }, { icon: '🤐', word: 'Zipper' }, { icon: '🦁', word: 'Zoo' }, { icon: '🥒', word: 'Zucchini' }, { icon: '💤', word: 'Zzz' }],
};
